{
 "title": "nimon按序列号整机监控_for_AIX_&_VIOS",
 "description": "Whole Server selected by Server Serial Number",
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "SerialNo",
    "label": "服务器（序列号）",
    "query": "SHOW TAG VALUES WITH KEY = \"serial_no\""
   }
  ]
 },
 "panels": [
  {
   "title": "Data connected by .........",
   "type": "text",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 0 },
   "options": {
    "content": "<center><img src=\"/public/logo/nimon_logo_${SerialNo}.png\"></img></center>"
   },
   "targets": [
    {
     "alias": "[[tag_host]]",
     "groupBy": [
      { "params": [ "host" ], "type": "tag" }
     ],
     "measurement": "cpu_physical_total",
     "query": "SELECT last(\"processorModel\") FROM \"config\" WHERE (\"serial_no\" =~ /^$SerialNo$/) AND $timeFilter",
     "select": [
      [
       { "params": [ "user" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "serial_no", "operator": "=", "value": "7804930" }
     ]
    }
   ]
  },
  {
   "title": "服务器型号",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 3, "y": 0 },
   "format": "none",
   "valueName": "first",
   "targets": [
    {
     "alias": "[[tag_host]]",
     "groupBy": [
      { "params": [ "host" ], "type": "tag" }
     ],
     "measurement": "cpu_physical_total",
     "query": "SELECT last(\"processorModel\") FROM \"config\" WHERE (\"serial_no\" =~ /^$SerialNo$/) AND $timeFilter",
     "select": [
      [
       { "params": [ "user" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "serial_no", "operator": "=", "value": "7804930" }
     ]
    }
   ]
  },
  {
   "title": "CPU核数",
   "type": "singlestat",
   "description": "整机CPU核数",
   "gridPos": { "h": 3, "w": 2, "x": 7, "y": 0 },
   "format": "none",
   "valueName": "first",
   "targets": [
    {
     "alias": "[[tag_host]]",
     "groupBy": [
      { "params": [ "host" ], "type": "tag" }
     ],
     "measurement": "cpu_physical_total",
     "query": "SELECT last(\"pcpu_online\") FROM \"config\" WHERE \"serial_no\" =~ /^$SerialNo$/ AND $timeFilter",
     "select": [
      [
       { "params": [ "user" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "serial_no", "operator": "=", "value": "7804930" }
     ]
    }
   ]
  },
  {
   "title": "已分配CPU数",
   "type": "singlestat",
   "description": "已分配CPU数",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 0 },
   "format": "none",
   "valueName": "first",
   "targets": [
    {
     "alias": "[[tag_serial_no]]",
     "groupBy": [
      { "params": [ "host" ], "type": "tag" }
     ],
     "measurement": "cpu_physical_total",
     "query": "SELECT sum(\"entitled_proc_capacity\")  FROM \"config\" WHERE (\"serial_no\" =~ /^$SerialNo$/) AND $timeFilter  group by time(5s)",
     "select": [
      [
       { "params": [ "user" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "serial_no", "operator": "=", "value": "7804930" }
     ]
    }
   ]
  },
  {
   "title": "CPU已分配率(%)",
   "type": "bargauge",
   "description": "CPU已分配率(%)",
   "gridPos": { "h": 3, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "first" ] } },
   "targets": [
    {
     "alias": "[[tag_serial_no]]",
     "groupBy": [
      { "params": [ "host" ], "type": "tag" }
     ],
     "measurement": "cpu_physical_total",
     "query": "SELECT sum(\"entitled_proc_capacity\") * 100 / last(\"pcpu_max\") FROM \"config\" WHERE (\"serial_no\" =~ /^$SerialNo$/) AND $timeFilter group by time(5s)",
     "select": [
      [
       { "params": [ "user" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "serial_no", "operator": "=", "value": "7804930" }
     ]
    }
   ]
  },
  {
   "title": "整机已用CPU核数",
   "type": "graph",
   "description": "整机已用CPU核数",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 3 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "[[tag_host]]",
     "groupBy": [
      { "params": [ "host" ], "type": "tag" }
     ],
     "measurement": "cpu_physical_total",
     "query": "SELECT sum(\"physical_busy\") FROM \"cpu_util\" WHERE (\"serial_no\" =~ /^$SerialNo$/ AND \"os\" = 'AIX' ) AND $timeFilter  GROUP BY  time(5s)",
     "select": [
      [
       { "params": [ "user" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "serial_no", "operator": "=", "value": "7804930" }
     ]
    }
   ]
  },
  {
   "title": "各分区已用CPU核数",
   "type": "graph",
   "description": "各分区已用CPU核数",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 3 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "[[tag_host]]",
     "groupBy": [
      { "params": [ "host" ], "type": "tag" }
     ],
     "measurement": "cpu_physical_total",
     "query": "SELECT \"physical_consumed\" FROM \"cpu_util\" WHERE (\"serial_no\" =~ /^$SerialNo$/ AND \"os\" = 'AIX' ) AND $timeFilter  GROUP BY host",
     "select": [
      [
       { "params": [ "user" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "serial_no", "operator": "=", "value": "7804930" }
     ]
    }
   ]
  },
  {
   "title": "CPU运行队列(Run Queue)",
   "type": "heatmap",
   "description": "CPU运行队列(Run Queue)",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 12 },
   "targets": [
    {
     "alias": "[[tag_host]]",
     "groupBy": [
      { "params": [ "host" ], "type": "tag" }
     ],
     "measurement": "disk_total",
     "query": "SELECT \"run_queue\" FROM \"kernel\" WHERE (\"serial_no\" =~ /^$SerialNo$/ AND \"os\" = 'AIX') AND $timeFilter GROUP BY \"host\"",
     "select": [
      [
       { "params": [ "read_blks" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "serial_no", "operator": "=", "value": "7804930" }
     ]
    }
   ]
  },
  {
   "title": "各分区CPU利用率(%)",
   "type": "graph",
   "description": "User + System + Wait",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "[[tag_host]]",
     "groupBy": [
      { "params": [ "host" ], "type": "tag" }
     ],
     "measurement": "cpu_physical_total",
     "query": "SELECT \"user\"+\"sys\"+\"wait\" FROM \"cpu_physical_total\" WHERE (\"serial_no\" =~ /^$SerialNo$/ AND \"os\" = 'AIX') AND $timeFilter GROUP BY \"host\"",
     "select": [
      [
       { "params": [ "user" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "serial_no", "operator": "=", "value": "7804930" }
     ]
    }
   ]
  },
  {
   "title": "计算内存百分比(%)",
   "type": "gauge",
   "description": "计算内存百分比(%)， 计算内存使用量 / 总物理内存",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 19 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "alias": "[[tag_host]]",
     "groupBy": [
      { "params": [ "host" ], "type": "tag" }
     ],
     "measurement": "memory",
     "query": "SELECT  (\"real_total\" - \"real_free\" - \"numperm\")  * 100 / \"real_total\"   FROM \"memory\" WHERE (\"serial_no\" =~ /^$SerialNo$/ AND \"os\" = 'AIX') AND $timeFilter GROUP BY \"host\"",
     "select": [
      [
       { "params": [ "real_inuse" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "serial_no", "operator": "=~", "value": "/^$SerialNo$/" },
      { "condition": "AND", "key": "os", "operator": "=", "value": "AIX" }
     ]
    }
   ]
  },
  {
   "title": "物理内存使用量(MB)",
   "type": "graph",
   "description": "物理内存使用量",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "[[tag_host]]",
     "groupBy": [
      { "params": [ "host" ], "type": "tag" }
     ],
     "measurement": "memory",
     "query": "SELECT  (\"real_total\" - \"real_free\" )  * 4096 / 1024 / 1024  FROM \"memory\" WHERE (\"serial_no\" =~ /^$SerialNo$/ AND \"os\" = 'AIX') AND $timeFilter GROUP BY \"host\"",
     "select": [
      [
       { "params": [ "real_inuse" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "serial_no", "operator": "=~", "value": "/^$SerialNo$/" },
      { "condition": "AND", "key": "os", "operator": "=", "value": "AIX" }
     ]
    }
   ]
  },
  {
   "title": "计算内存使用量(MB)",
   "type": "graph",
   "description": "计算内存使用量",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 28 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "[[tag_host]]",
     "groupBy": [
      { "params": [ "host" ], "type": "tag" }
     ],
     "measurement": "memory",
     "query": "SELECT  (\"real_total\" - \"real_free\" - \"numperm\")  * 4096 / 1024 / 1024  FROM \"memory\" WHERE (\"serial_no\" =~ /^$SerialNo$/ AND \"os\" = 'AIX') AND $timeFilter GROUP BY \"host\"",
     "select": [
      [
       { "params": [ "real_inuse" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "serial_no", "operator": "=~", "value": "/^$SerialNo$/" },
      { "condition": "AND", "key": "os", "operator": "=", "value": "AIX" }
     ]
    }
   ]
  },
  {
   "title": "交换空间百分比(%)",
   "type": "graph",
   "description": "交换空间百分比(%)",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 30 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "alias": "[[tag_host]]",
     "groupBy": [
      { "params": [ "host" ], "type": "tag" }
     ],
     "measurement": "memory",
     "query": "SELECT  (\"mb_used\" * 100 / \"mb_size\")  FROM \"paging_spaces\" WHERE (\"serial_no\" =~ /^$SerialNo$/ AND \"os\" = 'AIX') AND $timeFilter GROUP BY \"host\"",
     "select": [
      [
       { "params": [ "real_inuse" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "serial_no", "operator": "=~", "value": "/^$SerialNo$/" },
      { "condition": "AND", "key": "os", "operator": "=", "value": "AIX" }
     ]
    }
   ]
  },
  {
   "title": "各Disk繁忙百分比(%)",
   "type": "graph",
   "description": "各Disk繁忙百分比(%)",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 37 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "[[tag_host]],[[tag_disk_name]]",
     "groupBy": [
      { "params": [ "host" ], "type": "tag" }
     ],
     "measurement": "disk_total",
     "query": "SELECT   \"busy\" FROM \"disks\" WHERE (\"serial_no\" =~ /^$SerialNo$/ AND \"os\" = 'AIX') AND $timeFilter GROUP BY \"host\", \"disk_name\"",
     "select": [
      [
       { "params": [ "read_blks" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "serial_no", "operator": "=", "value": "7804930" }
     ]
    }
   ]
  },
  {
   "title": "网络包错误率（%）",
   "type": "bargauge",
   "description": "网络包错误率（%）",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 39 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "alias": "[[tag_host]]",
     "groupBy": [
      { "params": [ "host" ], "type": "tag" }
     ],
     "measurement": "network_total",
     "query": "SELECT (\"ierrors\" + \"oerrors\") * 100 /  (\"ipackets\"  + \"opackets\")   FROM \"network_total\" WHERE (\"serial_no\" =~ /^$SerialNo$/ AND \"os\" = 'AIX') AND $timeFilter GROUP BY \"host\"",
     "select": [
      [
       { "params": [ "ibytes" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "serial_no", "operator": "=", "value": "7804930" }
     ]
    }
   ]
  },
  {
   "title": "Disk平均IOPS",
   "type": "graph",
   "description": "Disk平均IOPS",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 44 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "[[tag_host]]",
     "groupBy": [
      { "params": [ "host" ], "type": "tag" }
     ],
     "measurement": "disk_total",
     "query": "SELECT   \"xfers\" FROM \"disk_total\" WHERE (\"serial_no\" =~ /^$SerialNo$/ AND \"os\" = 'AIX') AND $timeFilter GROUP BY \"host\"",
     "select": [
      [
       { "params": [ "read_blks" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "serial_no", "operator": "=", "value": "7804930" }
     ]
    }
   ]
  },
  {
   "title": "网络流量(Bytes/S)",
   "type": "graph",
   "description": "网络流量，单位Bytes",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 48 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "alias": "[[tag_host]].[[tag_network_interface_name]].in",
     "groupBy": [
      { "params": [ "host" ], "type": "tag" }
     ],
     "measurement": "network_total",
     "query": "SELECT \"ibytes\" FROM \"network_interfaces\" WHERE (\"serial_no\" =~ /^$SerialNo$/ AND \"os\" = 'AIX') AND $timeFilter GROUP BY \"host\", \"network_interface_name\"",
     "select": [
      [
       { "params": [ "ibytes" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "serial_no", "operator": "=", "value": "7804930" }
     ]
    },
    {
     "alias": "[[tag_host]].[[tag_network_interface_name]].out",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT \"obytes\" * -1  FROM \"network_interfaces\"  WHERE (\"serial_no\" =~ /^$SerialNo$/ AND \"os\" = 'AIX') AND $timeFilter GROUP BY \"host\", \"network_interface_name\"",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Disk IO读写吞吐量(MB/S)",
   "type": "graph",
   "description": "Disk IO读写吞吐量(MB/S)",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 53 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "[[tag_host]].write",
     "groupBy": [
      { "params": [ "host" ], "type": "tag" }
     ],
     "measurement": "disk_total",
     "query": "SELECT   \"write_blks\" * 512 / 1024 / 1024 FROM \"disk_total\" WHERE (\"serial_no\" =~ /^$SerialNo$/ AND \"os\" = 'AIX') AND $timeFilter GROUP BY \"host\"",
     "select": [
      [
       { "params": [ "read_blks" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "serial_no", "operator": "=", "value": "7804930" }
     ]
    },
    {
     "alias": "[[tag_host]].read",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT   \"read_blks\" * 512 / 1024 / 1024 FROM \"disk_total\" WHERE (\"serial_no\" =~ /^$SerialNo$/ AND \"os\" = 'AIX') AND $timeFilter GROUP BY \"host\"",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "网络包数量(/S)",
   "type": "graph",
   "description": "网络包数量",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 57 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "alias": "[[tag_host]].[[tag_network_interface_name]].in",
     "groupBy": [
      { "params": [ "host" ], "type": "tag" }
     ],
     "measurement": "network_total",
     "query": "SELECT \"ipackets\"  FROM \"network_interfaces\" WHERE (\"serial_no\" =~ /^$SerialNo$/ AND \"os\" = 'AIX') AND $timeFilter GROUP BY \"host\",\"network_interface_name\"",
     "select": [
      [
       { "params": [ "ibytes" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "serial_no", "operator": "=", "value": "7804930" }
     ]
    },
    {
     "alias": "[[tag_host]].[[tag_network_interface_name]].out",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT \"opackets\" * -1 FROM \"network_interfaces\" WHERE (\"serial_no\" =~ /^$SerialNo$/ AND \"os\" = 'AIX') AND $timeFilter GROUP BY \"host\",\"network_interface_name\"",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Disk IO平均相应时间(ms)",
   "type": "graph",
   "description": "Disk IO平均相应时间(ms)",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 62 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "[[tag_host]].write",
     "groupBy": [
      { "params": [ "host" ], "type": "tag" }
     ],
     "measurement": "disk_total",
     "query": "SELECT   \"wserv\" / 1000000000  FROM \"disk_total\" WHERE (\"serial_no\" =~ /^$SerialNo$/ AND \"os\" = 'AIX') AND $timeFilter GROUP BY \"host\"",
     "select": [
      [
       { "params": [ "read_blks" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "serial_no", "operator": "=", "value": "7804930" }
     ]
    },
    {
     "alias": "[[tag_host]].read",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT   \"rserv\" / 1000000000  FROM \"disk_total\" WHERE (\"serial_no\" =~ /^$SerialNo$/ AND \"os\" = 'AIX') AND $timeFilter GROUP BY \"host\"",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "各类进程占用CPU时间比例(%)",
   "type": "graph",
   "description": "各类进程占用CPU时间比例(%)",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 66 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "[[tag_host]],[[tag_processe_name]]",
     "groupBy": [
      { "params": [ "host" ], "type": "tag" }
     ],
     "measurement": "disk_total",
     "query": "SELECT  \"ucpu_time\" + \"scpu_time\" FROM \"processes\" WHERE (\"serial_no\" =~ /^$SerialNo$/ AND \"os\" = 'AIX') AND $timeFilter GROUP BY \"host\", \"processe_name\"",
     "select": [
      [
       { "params": [ "read_blks" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "serial_no", "operator": "=", "value": "7804930" }
     ]
    }
   ]
  },
  {
   "title": "Disk IO队列等待时间(ms)",
   "type": "graph",
   "description": "Disk IO队列等待时间(ms)",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 71 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "[[tag_host]]",
     "groupBy": [
      { "params": [ "host" ], "type": "tag" }
     ],
     "measurement": "disk_total",
     "query": "SELECT   \"wq_time\" / 1000000000  FROM \"disk_total\" WHERE (\"serial_no\" =~ /^$SerialNo$/ AND \"os\" = 'AIX') AND $timeFilter GROUP BY \"host\"",
     "select": [
      [
       { "params": [ "read_blks" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "serial_no", "operator": "=", "value": "7804930" }
     ]
    }
   ]
  },
  {
   "title": "各进程占用内存(KB)",
   "type": "graph",
   "description": "各进程占用内存(KB)",
   "gridPos": { "h": 14, "w": 12, "x": 12, "y": 75 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "[[tag_host]],[[tag_processe_name]]",
     "groupBy": [
      { "params": [ "host" ], "type": "tag" }
     ],
     "measurement": "disk_total",
     "query": "SELECT  \"real_inuse\" FROM \"processes\" WHERE (\"serial_no\" =~ /^$SerialNo$/ AND \"os\" = 'AIX') AND $timeFilter GROUP BY \"host\", \"processe_name\" ",
     "select": [
      [
       { "params": [ "read_blks" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "serial_no", "operator": "=", "value": "7804930" }
     ]
    }
   ]
  },
  {
   "title": "文件系统使用率(%)",
   "type": "graph",
   "description": "文件系统使用率(%)",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 80 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "alias": "[[tag_host]]:[[tag_filesystem_name]]",
     "groupBy": [
      { "params": [ "host" ], "type": "tag" }
     ],
     "measurement": "disk_total",
     "query": "SELECT \"used_percent\" FROM \"filesystems\" WHERE (\"serial_no\" =~ /^$SerialNo$/ AND \"os\" = 'AIX') AND $timeFilter GROUP BY \"host\",\"filesystem_name\"",
     "select": [
      [
       { "params": [ "read_blks" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "serial_no", "operator": "=", "value": "7804930" }
     ]
    }
   ]
  }
 ]
}