{
 "title": "nimon监控X86_Linux分区",
 "description": "njmon data gathers for Linux on any platform: AMD64, POWER8/9, Raspberry Pi and any Linux version\nIncludes 14 graphs of the regular CPU, memory, disks, filesystems and networks plus memory Pie charts and table view of memory extra stats.",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "LINUXHOST",
    "query": "SHOW TAG VALUES WITH KEY = \"host\" WHERE \"os\" != 'AIX'"
   }
  ]
 },
 "panels": [
  {
   "title": "数据收集 .........",
   "type": "text",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 0 },
   "options": {
    "content": "<center><img src=\"/public/logo/nimon_logo.png\"></img></center>\n\n\n\n"
   },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "主机名",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 3, "y": 0 },
   "format": "none",
   "valueName": "first",
   "targets": [
    {
     "measurement": "identity",
     "query": "SELECT \"name\" +  \"version\" FROM \"os_release\" WHERE (\"host\" =~ /^$LINUXHOST$/) AND $timeFilter",
     "select": [
      [
       { "params": [ "hostname" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$LINUXHOST$/" }
     ]
    }
   ]
  },
  {
   "title": "主机型号",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 6, "y": 0 },
   "format": "none",
   "valueName": "first",
   "targets": [
    {
     "measurement": "identity",
     "query": "SELECT \"name\" +  \"version\" FROM \"os_release\" WHERE (\"host\" =~ /^$LINUXHOST$/) AND $timeFilter",
     "select": [
      [
       { "params": [ "model" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$LINUXHOST$/" }
     ]
    }
   ]
  },
  {
   "title": "硬件架构",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 10, "y": 0 },
   "format": "none",
   "valueName": "first",
   "targets": [
    {
     "measurement": "lscpu",
     "query": "SELECT last(\"architecture\") FROM \"lscpu\" WHERE (\"host\" =~ /^$LINUXHOST$/) AND $timeFilter",
     "select": [
      [
       { "params": [ "architecture" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ],
      [
       { "params": [ "model" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$LINUXHOST$/" }
     ]
    }
   ]
  },
  {
   "title": "核数",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 12, "y": 0 },
   "format": "none",
   "valueName": "first",
   "targets": [
    {
     "measurement": "lscpu",
     "query": "SELECT last(\"architecture\") FROM \"lscpu\" WHERE (\"host\" =~ /^$LINUXHOST$/) AND $timeFilter",
     "select": [
      [
       { "params": [ "threads_per_core" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$LINUXHOST$/" }
     ]
    }
   ]
  },
  {
   "title": "服务器序列号",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 6, "x": 14, "y": 0 },
   "format": "none",
   "valueName": "first",
   "targets": [
    {
     "measurement": "identity",
     "query": "SELECT last(\"serial-number\") FROM \"identity\" WHERE (\"host\" =~ /^$LINUXHOST$/) AND $timeFilter",
     "select": [
      [
       { "params": [ "system-id" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$LINUXHOST$/" }
     ]
    }
   ]
  },
  {
   "title": "系统时间",
   "type": "grafana-clock-panel",
   "description": "系统时间",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 0 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT mean(\"value\") FROM \"measurement\" WHERE $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "操作系统",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 7, "x": 3, "y": 2 },
   "format": "none",
   "valueName": "first",
   "targets": [
    {
     "measurement": "os_release",
     "query": "SELECT \"name\" +  \"version\" FROM \"os_release\" WHERE (\"host\" =~ /^$LINUXHOST$/) AND $timeFilter",
     "select": [
      [
       { "params": [ "name" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$LINUXHOST$/" }
     ]
    }
   ]
  },
  {
   "title": "操作系统版本",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 10, "y": 2 },
   "format": "none",
   "valueName": "first",
   "targets": [
    {
     "measurement": "os_release",
     "query": "SELECT \"name\" +  \"version\" FROM \"os_release\" WHERE (\"host\" =~ /^$LINUXHOST$/) AND $timeFilter",
     "select": [
      [
       { "params": [ "version_id" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$LINUXHOST$/" }
     ]
    }
   ]
  },
  {
   "title": "逻辑CPU核数",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 12, "y": 2 },
   "format": "none",
   "valueName": "first",
   "targets": [
    {
     "measurement": "lscpu",
     "query": "SELECT last(\"architecture\") FROM \"lscpu\" WHERE (\"host\" =~ /^$LINUXHOST$/) AND $timeFilter",
     "select": [
      [
       { "params": [ "online_cpu_list" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$LINUXHOST$/" }
     ]
    }
   ]
  },
  {
   "title": "处理器型号",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 6, "x": 14, "y": 2 },
   "format": "none",
   "valueName": "first",
   "targets": [
    {
     "measurement": "lscpu",
     "query": "SELECT last(\"architecture\") FROM \"lscpu\" WHERE (\"host\" =~ /^$LINUXHOST$/) AND $timeFilter",
     "select": [
      [
       { "params": [ "model_name" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$LINUXHOST$/" }
     ]
    }
   ]
  },
  {
   "title": "CPU利用率",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 4 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "User",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "cpu_total",
     "select": [
      [
       { "params": [ "user" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$LINUXHOST$/" }
     ]
    },
    {
     "alias": "System",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "cpu_total",
     "select": [
      [
       { "params": [ "sys" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$LINUXHOST$/" }
     ]
    },
    {
     "alias": "Steal",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "cpu_total",
     "select": [
      [
       { "params": [ "steal" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$LINUXHOST$/" }
     ]
    },
    {
     "alias": "SoftIRQ",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "cpu_total",
     "select": [
      [
       { "params": [ "softirq" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$LINUXHOST$/" }
     ]
    },
    {
     "alias": "HardIRQ",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "cpu_total",
     "select": [
      [
       { "params": [ "hardirq" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$LINUXHOST$/" }
     ]
    },
    {
     "alias": "Nice",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "cpu_total",
     "select": [
      [
       { "params": [ "nice" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$LINUXHOST$/" }
     ]
    },
    {
     "alias": "IOwait",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "cpu_total",
     "select": [
      [
       { "params": [ "iowait" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$LINUXHOST$/" }
     ]
    },
    {
     "alias": "Guest",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "cpu_total",
     "select": [
      [
       { "params": [ "guest" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$LINUXHOST$/" }
     ]
    },
    {
     "alias": "GuestNice",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "cpu_total",
     "select": [
      [
       { "params": [ "guestnice" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$LINUXHOST$/" }
     ]
    }
   ]
  },
  {
   "title": "CPU运行和阻塞队列",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 4 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Running",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "stat_counters",
     "select": [
      [
       { "params": [ "procs_running" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$LINUXHOST$/" }
     ]
    },
    {
     "alias": "Blocked",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "stat_counters",
     "select": [
      [
       { "params": [ "procs_blocked" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$LINUXHOST$/" }
     ]
    }
   ]
  },
  {
   "title": "fork进程数",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "fork",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "stat_counters",
     "select": [
      [
       { "params": [ "processes_forks" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$LINUXHOST$/" }
     ]
    }
   ]
  },
  {
   "title": "进程上下文切换",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "ctxt",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "stat_counters",
     "select": [
      [
       { "params": [ "ctxt" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$LINUXHOST$/" }
     ]
    }
   ]
  },
  {
   "title": "空闲/可用内存(MB)",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 20 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "alias": "Available",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "proc_meminfo",
     "query": "SELECT last(\"MemAvailable\")/1024 FROM \"proc_meminfo\" WHERE (\"host\" =~ /^$LINUXHOST$/) AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "MemAvailable" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$LINUXHOST$/" }
     ]
    },
    {
     "alias": "Free",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "proc_meminfo",
     "query": "SELECT last(\"MemFree\")/1024 FROM \"proc_meminfo\" WHERE (\"host\" =~ /^$LINUXHOST$/) AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "MemFree" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$LINUXHOST$/" }
     ]
    }
   ]
  },
  {
   "title": "Active/InActive内存(MB)",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 20 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "alias": "Active",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "proc_meminfo",
     "query": "SELECT last(\"Active\")/1024 FROM \"proc_meminfo\" WHERE (\"host\" =~ /^$LINUXHOST$/) AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "Active" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$LINUXHOST$/" }
     ]
    },
    {
     "alias": "Inactive",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "proc_meminfo",
     "query": "SELECT last(\"Inactive\")/1024 FROM \"proc_meminfo\" WHERE (\"host\" =~ /^$LINUXHOST$/) AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "Inactive" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$LINUXHOST$/" }
     ]
    }
   ]
  },
  {
   "title": "内存状态",
   "type": "table-old",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 20 },
   "targets": [
    {
     "alias": "Active",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "proc_meminfo",
     "query": "SELECT last(\"firmware\") FROM \"proc_meminfo\" WHERE (\"host\" =~ /^$LINUXHOST$/) AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "firmware" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$LINUXHOST$/" }
     ]
    },
    {
     "alias": "InActive",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "proc_meminfo",
     "query": "SELECT last(\"Inactive\")*1024 FROM \"proc_meminfo\" WHERE (\"host\" =~ /^$LINUXHOST$/) AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "Inactive" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$LINUXHOST$/" }
     ]
    },
    {
     "alias": "InActive_anon",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "proc_meminfo",
     "query": "SELECT last(\"Inactive_anon\")*1024 FROM \"proc_meminfo\" WHERE (\"host\" =~ /^$LINUXHOST$/) AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "Inactive_anon" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$LINUXHOST$/" }
     ]
    },
    {
     "alias": "Active_anon",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "proc_meminfo",
     "query": "SELECT last(\"Active_anon\")*1024 FROM \"proc_meminfo\" WHERE (\"host\" =~ /^$LINUXHOST$/) AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "Active_anon" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$LINUXHOST$/" }
     ]
    },
    {
     "alias": "Active_file",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "proc_meminfo",
     "query": "SELECT last(\"Active_file\")*1024 FROM \"proc_meminfo\" WHERE (\"host\" =~ /^$LINUXHOST$/) AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "Active_file" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$LINUXHOST$/" }
     ]
    },
    {
     "alias": "InActive_file",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "proc_meminfo",
     "query": "SELECT last(\"Inactive_file\")*1024 FROM \"proc_meminfo\" WHERE (\"host\" =~ /^$LINUXHOST$/) AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "Inactive_file" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$LINUXHOST$/" }
     ]
    },
    {
     "alias": "Buffers",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "proc_meminfo",
     "query": "SELECT last(\"Buffers\")*1024 FROM \"proc_meminfo\" WHERE (\"host\" =~ /^$LINUXHOST$/) AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "Buffers" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$LINUXHOST$/" }
     ]
    },
    {
     "alias": "Cached",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "proc_meminfo",
     "query": "SELECT last(\"Cached\")*1024 FROM \"proc_meminfo\" WHERE (\"host\" =~ /^$LINUXHOST$/) AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "Cached" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$LINUXHOST$/" }
     ]
    },
    {
     "alias": "CommitLimit",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "proc_meminfo",
     "query": "SELECT last(\"CommitLimit\")*1024 FROM \"proc_meminfo\" WHERE (\"host\" =~ /^$LINUXHOST$/) AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "CommitLimit" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$LINUXHOST$/" }
     ]
    },
    {
     "alias": "Dirty",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "proc_meminfo",
     "query": "SELECT last(\"Dirty\")*1024 FROM \"proc_meminfo\" WHERE (\"host\" =~ /^$LINUXHOST$/) AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "Dirty" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$LINUXHOST$/" }
     ]
    },
    {
     "alias": "KernelStack",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "proc_meminfo",
     "query": "SELECT last(\"KernelStack\")*1024 FROM \"proc_meminfo\" WHERE (\"host\" =~ /^$LINUXHOST$/) AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "KernelStack" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$LINUXHOST$/" }
     ]
    },
    {
     "alias": "Mapped",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "proc_meminfo",
     "query": "SELECT last(\"Mapped\")*1024 FROM \"proc_meminfo\" WHERE (\"host\" =~ /^$LINUXHOST$/) AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "Mapped" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$LINUXHOST$/" }
     ]
    },
    {
     "alias": "MemAvailable",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "proc_meminfo",
     "query": "SELECT last(\"MemAvailable\")*1024 FROM \"proc_meminfo\" WHERE (\"host\" =~ /^$LINUXHOST$/) AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "MemAvailable" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$LINUXHOST$/" }
     ]
    },
    {
     "alias": "MemFree",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "proc_meminfo",
     "query": "SELECT last(\"MemFree\")*1024 FROM \"proc_meminfo\" WHERE (\"host\" =~ /^$LINUXHOST$/) AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "MemFree" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$LINUXHOST$/" }
     ]
    },
    {
     "alias": "MemTotal",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "proc_meminfo",
     "query": "SELECT last(\"MemTotal\")*1024 FROM \"proc_meminfo\" WHERE (\"host\" =~ /^$LINUXHOST$/) AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "MemTotal" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$LINUXHOST$/" }
     ]
    },
    {
     "alias": "PageTables",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "proc_meminfo",
     "query": "SELECT last(\"PageTables\")*1024 FROM \"proc_meminfo\" WHERE (\"host\" =~ /^$LINUXHOST$/) AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "PageTables" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$LINUXHOST$/" }
     ]
    }
   ]
  },
  {
   "title": "总内存和空闲内存(MB)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 28 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "MemTotal",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "proc_meminfo",
     "query": "SELECT mean(\"MemTotal\")/1024 FROM \"proc_meminfo\" WHERE (\"host\" =~ /^$LINUXHOST$/) AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "MemTotal" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$LINUXHOST$/" }
     ]
    },
    {
     "alias": "MemFree",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "proc_meminfo",
     "query": "SELECT mean(\"MemFree\")/1024 FROM \"proc_meminfo\" WHERE (\"host\" =~ /^$LINUXHOST$/) AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "MemFree" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$LINUXHOST$/" }
     ]
    },
    {
     "alias": "MemAvailable",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "proc_meminfo",
     "query": "SELECT mean(\"MemAvailable\")/1024 FROM \"proc_meminfo\" WHERE (\"host\" =~ /^$LINUXHOST$/) AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "MemAvailable" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$LINUXHOST$/" }
     ]
    }
   ]
  },
  {
   "title": "Active/Inactive内存",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 28 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Active",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "proc_meminfo",
     "select": [
      [
       { "params": [ "Active" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$LINUXHOST$/" }
     ]
    },
    {
     "alias": "InActive",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "proc_meminfo",
     "select": [
      [
       { "params": [ "Inactive" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$LINUXHOST$/" }
     ]
    }
   ]
  },
  {
   "title": "交换空间大小(MB)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 36 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Total",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "proc_meminfo",
     "query": "SELECT mean(\"SwapTotal\")/1024 FROM \"proc_meminfo\" WHERE (\"host\" =~ /^$LINUXHOST$/) AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "SwapTotal" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$LINUXHOST$/" }
     ]
    },
    {
     "alias": "Free",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "proc_meminfo",
     "query": "SELECT mean(\"SwapFree\")/1024 FROM \"proc_meminfo\" WHERE (\"host\" =~ /^$LINUXHOST$/) AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "SwapFree" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$LINUXHOST$/" }
     ]
    },
    {
     "alias": "Cached",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "proc_meminfo",
     "query": "SELECT mean(\"SwapCached\")/1024 FROM \"proc_meminfo\" WHERE (\"host\" =~ /^$LINUXHOST$/) AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "SwapCached" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$LINUXHOST$/" }
     ]
    }
   ]
  },
  {
   "title": "换页率",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 36 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Paging_page_in",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "proc_vmstat",
     "query": "SELECT mean(\"pgpgin\") FROM \"proc_vmstat\" WHERE (\"host\" =~ /^$LINUXHOST$/) AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "pgpgin" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$LINUXHOST$/" }
     ]
    },
    {
     "alias": "Paging_page_out",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "proc_vmstat",
     "select": [
      [
       { "params": [ "pgpgout" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$LINUXHOST$/" }
     ]
    },
    {
     "alias": "Paging_swap_in",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "proc_vmstat",
     "select": [
      [
       { "params": [ "pswpin" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$LINUXHOST$/" }
     ]
    },
    {
     "alias": "Paging_swap_out",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "proc_vmstat",
     "select": [
      [
       { "params": [ "pswpout" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$LINUXHOST$/" }
     ]
    }
   ]
  },
  {
   "title": "磁盘吞吐量(KB/sec)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 44 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "[[tag_disk_name]].Read",
     "groupBy": [
      { "params": [ "disk_name" ], "type": "tag" }
     ],
     "measurement": "disks",
     "select": [
      [
       { "params": [ "rkb" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$LINUXHOST$/" }
     ]
    },
    {
     "alias": "[[tag_disk_name]].Write",
     "groupBy": [
      { "params": [ "disk_name" ], "type": "tag" }
     ],
     "measurement": "disks",
     "select": [
      [
       { "params": [ "wkb" ], "type": "field" },
       { "params": [ "*  -1" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$LINUXHOST$/" }
     ]
    }
   ]
  },
  {
   "title": "磁盘读写块数",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 44 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "[[tag_disk_name]].Read",
     "groupBy": [
      { "params": [ "disk_name" ], "type": "tag" }
     ],
     "measurement": "disks",
     "select": [
      [
       { "params": [ "reads" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$LINUXHOST$/" }
     ]
    },
    {
     "alias": "[[tag_disk_name]].Write",
     "groupBy": [
      { "params": [ "disk_name" ], "type": "tag" }
     ],
     "measurement": "disks",
     "select": [
      [
       { "params": [ "writes" ], "type": "field" },
       { "params": [ "*  -1" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$LINUXHOST$/" }
     ]
    }
   ]
  },
  {
   "title": "磁盘繁忙度(%)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 52 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "[[tag_disk_name]].Busy",
     "groupBy": [
      { "params": [ "disk_name" ], "type": "tag" }
     ],
     "measurement": "disks",
     "query": "SELECT \"busy\"*100 FROM \"disks\" WHERE (\"host\" =~ /^$LINUXHOST$/) AND $timeFilter GROUP BY \"disk_name\"",
     "select": [
      [
       { "params": [ "busy" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$LINUXHOST$/" }
     ]
    }
   ]
  },
  {
   "title": "文件系统空闲空间(MB)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 52 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "[[tag_filesystem_name]]",
     "groupBy": [
      { "params": [ "filesystem_name" ], "type": "tag" }
     ],
     "measurement": "filesystems",
     "select": [
      [
       { "params": [ "fs_free_mb" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$LINUXHOST$/" }
     ]
    }
   ]
  },
  {
   "title": "网络进/出流量(Bytes)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 60 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "[[tag_network_name]].ibytes",
     "groupBy": [
      { "params": [ "network_name" ], "type": "tag" }
     ],
     "measurement": "networks",
     "select": [
      [
       { "params": [ "ibytes" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$LINUXHOST$/" }
     ]
    },
    {
     "alias": "[[tag_network_name]].obytes",
     "groupBy": [
      { "params": [ "network_name" ], "type": "tag" }
     ],
     "measurement": "networks",
     "select": [
      [
       { "params": [ "obytes" ], "type": "field" },
       { "params": [ "*  -1" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$LINUXHOST$/" }
     ]
    }
   ]
  },
  {
   "title": "网络进/出包数量",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 60 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "[[tag_network_name]].ipackets",
     "groupBy": [
      { "params": [ "network_name" ], "type": "tag" }
     ],
     "measurement": "networks",
     "select": [
      [
       { "params": [ "ipackets" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$LINUXHOST$/" }
     ]
    },
    {
     "alias": "[[tag_network_name]].opackets",
     "groupBy": [
      { "params": [ "network_name" ], "type": "tag" }
     ],
     "measurement": "networks",
     "select": [
      [
       { "params": [ "opackets" ], "type": "field" },
       { "params": [ "*  -1" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$LINUXHOST$/" }
     ]
    }
   ]
  },
  {
   "title": "NFS v4服务器访问",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 68 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Access",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "NFS4server",
     "select": [
      [
       { "params": [ "access" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$LINUXHOST$/" }
     ]
    }
   ]
  },
  {
   "title": "NFS v4客户端访问",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 68 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Access",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "NFS4client",
     "select": [
      [
       { "params": [ "access" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$LINUXHOST$/" }
     ]
    }
   ]
  }
 ]
}