{
 "title": "nimon监控AIX分区",
 "description": "Use njmon on AIX",
 "tags": [
  "AIX",
  "njmon",
  "Simple six",
  "Best Version"
 ],
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "HOST",
    "label": "Hostname",
    "query": "SHOW TAG VALUES WITH KEY = \"host\" WHERE os = 'AIX'"
   }
  ]
 },
 "panels": [
  {
   "title": "Data connected by .........",
   "type": "text",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 0 },
   "options": {
    "content": "<center><img src=\"/public/logo/nimon_logo.png\\\"></img></center>"
   },
   "targets": [
    {
     "alias": "Entitlement",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "cpu_util",
     "select": [
      [
       { "params": [ "entitlement" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$HOST$/" }
     ]
    },
    {
     "alias": "Consumed",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "cpu_util",
     "select": [
      [
       { "params": [ "physical_consumed" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$HOST$/" }
     ]
    },
    {
     "alias": "Virtual CPU",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "lpar_format2",
     "select": [
      [
       { "params": [ "online_vcpus" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$HOST$/" }
     ]
    }
   ]
  },
  {
   "title": "分区名",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 3, "y": 0 },
   "format": "none",
   "valueName": "first",
   "targets": [
    {
     "alias": "[[tag_host]]",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "kernel",
     "query": "SELECT last(\"partitionname\" ) FROM \"config\" WHERE (\"host\" =~ /^$HOST$/) AND $timeFilter",
     "select": [
      [
       { "params": [ "run_queue" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$HOST$/" }
     ]
    }
   ]
  },
  {
   "title": "服务器型号",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 5, "y": 0 },
   "format": "none",
   "valueName": "first",
   "targets": [
    {
     "alias": "[[tag_host]]",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "kernel",
     "query": "SELECT last(\"processorModel\" ) FROM \"config\" WHERE (\"host\" =~ /^$HOST$/) AND $timeFilter",
     "select": [
      [
       { "params": [ "run_queue" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$HOST$/" }
     ]
    }
   ]
  },
  {
   "title": "CPU SMT线程数",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 8, "y": 0 },
   "format": "none",
   "valueName": "first",
   "targets": [
    {
     "alias": "[[tag_host]]",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "kernel",
     "query": "SELECT last(\"smtthreads\" ) FROM \"config\" WHERE (\"host\" =~ /^$HOST$/) AND $timeFilter",
     "select": [
      [
       { "params": [ "run_queue" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$HOST$/" }
     ]
    }
   ]
  },
  {
   "title": "操作系统",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 11, "y": 0 },
   "format": "none",
   "valueName": "first",
   "targets": [
    {
     "alias": "[[tag_host]]",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "kernel",
     "query": "SELECT last(\"OSname\" ) FROM \"config\" WHERE (\"host\" =~ /^$HOST$/) AND $timeFilter",
     "select": [
      [
       { "params": [ "run_queue" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$HOST$/" }
     ]
    }
   ]
  },
  {
   "title": "CPU模式（0共享/1独占)",
   "type": "singlestat",
   "description": "CPU模式（0共享/1独占)",
   "gridPos": { "h": 2, "w": 3, "x": 13, "y": 0 },
   "format": "none",
   "valueName": "first",
   "targets": [
    {
     "alias": "[[tag_host]]",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "kernel",
     "query": "SELECT floor(\"capacity_increment\") FROM \"lpar_format1\" WHERE (\"host\" =~ /^$HOST$/) AND $timeFilter",
     "select": [
      [
       { "params": [ "run_queue" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$HOST$/" }
     ]
    }
   ]
  },
  {
   "title": "分区在线CPU核数(VP)",
   "type": "singlestat",
   "description": "分区在线CPU核数(VP)",
   "gridPos": { "h": 2, "w": 3, "x": 16, "y": 0 },
   "format": "none",
   "valueName": "first",
   "targets": [
    {
     "alias": "[[tag_host]]",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "kernel",
     "query": "SELECT last(\"online_vcpus\" ) FROM \"lpar_format2\" WHERE (\"host\" =~ /^$HOST$/) AND $timeFilter",
     "select": [
      [
       { "params": [ "run_queue" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$HOST$/" }
     ]
    }
   ]
  },
  {
   "title": "系统时间",
   "type": "grafana-clock-panel",
   "description": "系统时间",
   "gridPos": { "h": 4, "w": 5, "x": 19, "y": 0 },
   "targets": [
    {
     "alias": "[[tag_host]]",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "kernel",
     "query": "SELECT mean(\"value\") FROM \"measurement\" WHERE $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "run_queue" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$HOST$/" }
     ]
    }
   ]
  },
  {
   "title": "Hostname",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 3, "y": 2 },
   "format": "none",
   "valueName": "first",
   "targets": [
    {
     "alias": "[[tag_host]]",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "kernel",
     "query": "SELECT last(\"nodename\" ) FROM \"config\" WHERE (\"host\" =~ /^$HOST$/) AND $timeFilter",
     "select": [
      [
       { "params": [ "run_queue" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$HOST$/" }
     ]
    }
   ]
  },
  {
   "title": "CPU型号",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 5, "y": 2 },
   "format": "none",
   "valueName": "first",
   "targets": [
    {
     "alias": "[[tag_host]]",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "kernel",
     "query": "SELECT last(\"processorFamily\" ) FROM \"config\" WHERE (\"host\" =~ /^$HOST$/) AND $timeFilter",
     "select": [
      [
       { "params": [ "run_queue" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$HOST$/" }
     ]
    }
   ]
  },
  {
   "title": "分区内存配置（MB）",
   "type": "singlestat",
   "description": "分区内存配置（MB）",
   "gridPos": { "h": 2, "w": 3, "x": 8, "y": 2 },
   "format": "none",
   "valueName": "first",
   "targets": [
    {
     "alias": "[[tag_host]]",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "kernel",
     "query": "SELECT last(\"mem_online\" ) FROM \"config\" WHERE (\"host\" =~ /^$HOST$/) AND $timeFilter",
     "select": [
      [
       { "params": [ "run_queue" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$HOST$/" }
     ]
    }
   ]
  },
  {
   "title": "操作系统版本",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 11, "y": 2 },
   "format": "none",
   "valueName": "first",
   "targets": [
    {
     "alias": "[[tag_host]]",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "kernel",
     "query": "SELECT last(\"OSversion\" ) FROM \"config\" WHERE (\"host\" =~ /^$HOST$/) AND $timeFilter",
     "select": [
      [
       { "params": [ "run_queue" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$HOST$/" }
     ]
    }
   ]
  },
  {
   "title": "分区期望CPU核数(PU)",
   "type": "singlestat",
   "description": "分区期望CPU核数(PU)",
   "gridPos": { "h": 2, "w": 3, "x": 13, "y": 2 },
   "format": "none",
   "valueName": "first",
   "targets": [
    {
     "alias": "[[tag_host]]",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "kernel",
     "query": "SELECT last(\"entitled_capacity\" ) FROM \"lpar_format2\" WHERE (\"host\" =~ /^$HOST$/) AND $timeFilter",
     "select": [
      [
       { "params": [ "run_queue" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$HOST$/" }
     ]
    }
   ]
  },
  {
   "title": "分区最大CPU核数(VP)",
   "type": "singlestat",
   "description": "分区最大CPU核数(VP)",
   "gridPos": { "h": 2, "w": 3, "x": 16, "y": 2 },
   "format": "none",
   "valueName": "first",
   "targets": [
    {
     "alias": "[[tag_host]]",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "kernel",
     "query": "SELECT last(\"max_vcpus\" ) FROM \"lpar_format1\" WHERE (\"host\" =~ /^$HOST$/) AND $timeFilter",
     "select": [
      [
       { "params": [ "run_queue" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$HOST$/" }
     ]
    }
   ]
  },
  {
   "title": "CPU消耗, 期望CPU(Entitlement), VP数量",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 4 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "期望CPU(Entitlement)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "cpu_util",
     "query": "SELECT mean(\"entitlement\") FROM \"cpu_util\" WHERE (\"host\" =~ /^$HOST$/) AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "entitlement" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$HOST$/" }
     ]
    },
    {
     "alias": "CPU消耗",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "cpu_util",
     "query": "SELECT mean(\"physical_busy\") FROM \"cpu_util\" WHERE (\"host\" =~ /^$HOST$/) AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "physical_consumed" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$HOST$/" }
     ]
    },
    {
     "alias": "VP数量",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "lpar_format2",
     "select": [
      [
       { "params": [ "online_vcpus" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$HOST$/" }
     ]
    }
   ]
  },
  {
   "title": "CPU利用率(%)",
   "type": "graph",
   "description": "CPU利用率(%)",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 4 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "CPU利用率",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "cpu_physical_total",
     "query": "SELECT \"user\"+\"sys\"+\"wait\" FROM \"cpu_physical_total\"  WHERE (\"host\" =~ /^$HOST$/) AND $timeFilter ",
     "select": [
      [
       { "params": [ "sys" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$HOST$/" }
     ]
    },
    {
     "alias": "CPU USER平均利用率趋势线",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT MOVING_AVERAGE(\"user\",600) FROM \"cpu_physical_total\"  WHERE (\"host\" =~ /^$HOST$/) AND $timeFilter ",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "CPU SYS平均利用率趋势线",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT MOVING_AVERAGE(\"sys\",600) FROM \"cpu_physical_total\"  WHERE (\"host\" =~ /^$HOST$/) AND $timeFilter ",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "CPU运行队列(Run Queue)",
   "type": "heatmap",
   "description": "CPU运行队列(Run Queue)",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 11 },
   "targets": [
    {
     "alias": "Run Queue",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "kernel",
     "query": "SELECT mean(\"run_queue\") FROM \"kernel\" WHERE (\"host\" =~ /^$HOST$/) AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "run_queue" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$HOST$/" }
     ]
    }
   ]
  },
  {
   "title": "CPU USER利用率预测(%)",
   "type": "graph",
   "description": "CPU USER利用率预测(%)",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 11 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "cpu_physical_total",
     "query": "SELECT HOLT_WINTERS_WITH_FIT(mean(\"user\"),1200,40), mean(\"user\") FROM \"cpu_physical_total\"  WHERE (\"host\" =~ /^$HOST$/) AND $timeFilter  GROUP BY time(36m,40m)",
     "select": [
      [
       { "params": [ "sys" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$HOST$/" }
     ]
    }
   ]
  },
  {
   "title": "内存使用情况（MB）",
   "type": "graph",
   "description": "内存使用情况（MB）",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "alias": "系统使用内存",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "memory",
     "query": "SELECT mean(\"real_system\") *4096/1024/1024 FROM \"memory\" WHERE (\"host\" =~ /^$HOST$/) AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "real_system" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "*4096/1024/1024" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$HOST$/" }
     ]
    },
    {
     "alias": "进程使用内存",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "memory",
     "select": [
      [
       { "params": [ "real_process" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "*4096/1024/1024" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$HOST$/" }
     ]
    },
    {
     "alias": "文件系统缓存",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "memory_page",
     "select": [
      [
       { "params": [ "numperm" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "*4096/1024/1024" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$HOST$/" }
     ]
    },
    {
     "alias": "空闲",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "memory",
     "select": [
      [
       { "params": [ "real_free" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "*4096/1024/1024" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$HOST$/" }
     ]
    },
    {
     "alias": "分区配置内存",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "memory",
     "query": "SELECT mean(\"real_total\") *4096/1024/1024 FROM \"memory\" WHERE (\"host\" =~ /^$HOST$/) AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "real_total" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "*4096/1024/1024" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$HOST$/" }
     ]
    },
    {
     "alias": "计算内存",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT  (\"real_total\" - \"real_free\" - \"numperm\") *4096/1024/1024 FROM \"memory\" WHERE (\"host\" =~ /^$HOST$/) AND $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "内存百分比(%)",
   "type": "gauge",
   "description": "内存百分比(%)",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 19 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "alias": "计算内存百分比(%)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT  (\"real_total\" - \"real_free\" - \"numperm\")  * 100 / \"real_total\"   FROM \"memory\"  WHERE (\"host\" =~ /^$HOST$/) AND $timeFilter ",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "文件缓存百分比(%)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT  (\"numperm\")  * 100 / \"real_total\"   FROM \"memory\"  WHERE (\"host\" =~ /^$HOST$/) AND $timeFilter ",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Disk IOPS",
   "type": "graph",
   "description": "Disk IOPS",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "alias": "总IOPS",
     "groupBy": [
      { "params": [ "network_interface_name" ], "type": "tag" }
     ],
     "measurement": "network_interfaces",
     "query": "SELECT   \"xfers\" FROM \"disk_total\" WHERE (\"host\" =~ /^$HOST$/) AND $timeFilter",
     "select": [
      [
       { "params": [ "ibytes" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$HOST$/" }
     ]
    },
    {
     "alias": "[[tag_disk_name]]",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT   \"xfers\" FROM \"disks\" WHERE (\"host\" =~ /^$HOST$/) AND $timeFilter GROUP BY \"disk_name\"",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "内存使用百分比(%)",
   "type": "graph",
   "description": "内存使用百分比(%)",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "alias": "文件系统缓存百分比",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "memory_page",
     "query": "SELECT \"numperm\"*100/\"real_total\" FROM \"memory_page\" WHERE (\"host\" =~ /^$HOST$/) AND $timeFilter ",
     "select": [
      [
       { "params": [ "numperm" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "*4096/1024/1024" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$HOST$/" }
     ]
    },
    {
     "alias": "系统使用内存百分比",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "memory",
     "query": "SELECT \"real_system\"*100/\"real_total\" FROM \"memory\" WHERE (\"host\" =~ /^$HOST$/) AND $timeFilter ",
     "select": [
      [
       { "params": [ "real_system" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "*4096/1024/1024" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$HOST$/" }
     ]
    },
    {
     "alias": "进程使用内存百分比",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "memory",
     "query": "SELECT \"real_process\"*100/\"real_total\" FROM \"memory\" WHERE (\"host\" =~ /^$HOST$/) AND $timeFilter ",
     "select": [
      [
       { "params": [ "real_process" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "*4096/1024/1024" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$HOST$/" }
     ]
    },
    {
     "alias": "计算内存百分比",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT  (\"real_total\" - \"real_free\" - \"numperm\")*100/\"real_total\" FROM \"memory\" WHERE (\"host\" =~ /^$HOST$/) AND $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "空闲百分比",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "memory",
     "query": "SELECT  (\"real_total\" - \"real_free\" - \"numperm\")*100/\"real_total\" FROM \"memory\" WHERE (\"host\" =\"racnode1\") AND $timeFilter",
     "select": [
      [
       { "params": [ "real_free" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "*4096/1024/1024" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$HOST$/" }
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "网络包错误率（%）",
   "type": "bargauge",
   "description": "网络包错误率（%）",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 34 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "alias": "网络包错误率",
     "groupBy": [
      { "params": [ "network_interface_name" ], "type": "tag" }
     ],
     "measurement": "network_interfaces",
     "query": "SELECT (\"ierrors\" + \"oerrors\") * 100 /  (\"ipackets\"  + \"opackets\")   FROM \"network_total\" WHERE (\"host\" =~ /^$HOST$/) AND $timeFilter ",
     "select": [
      [
       { "params": [ "ibytes" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$HOST$/" }
     ]
    }
   ]
  },
  {
   "title": "Disk繁忙程度百分比(%)",
   "type": "graph",
   "description": "Disk繁忙程度百分比(%)",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "alias": "[[tag_disk_name]]",
     "groupBy": [
      { "params": [ "network_interface_name" ], "type": "tag" }
     ],
     "measurement": "network_interfaces",
     "query": "SELECT   \"busy\" FROM \"disks\" WHERE (\"host\" =~ /^$HOST$/) AND $timeFilter  GROUP BY \"disk_name\"",
     "select": [
      [
       { "params": [ "ibytes" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$HOST$/" }
     ]
    }
   ]
  },
  {
   "title": "网络流量(Bytes/S)",
   "type": "graph",
   "description": "网络流量(Bytes/S)",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "alias": "[[tag_network_interface_name]].in",
     "groupBy": [
      { "params": [ "network_interface_name" ], "type": "tag" }
     ],
     "measurement": "network_interfaces",
     "query": "SELECT \"ibytes\" FROM \"network_interfaces\" WHERE (\"host\" =~ /^$HOST$/) AND $timeFilter GROUP BY \"network_interface_name\"",
     "select": [
      [
       { "params": [ "ibytes" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$HOST$/" }
     ]
    },
    {
     "alias": "[[tag_network_interface_name]].out",
     "groupBy": [
      { "params": [ "network_interface_name" ], "type": "tag" }
     ],
     "measurement": "network_interfaces",
     "select": [
      [
       { "params": [ "obytes" ], "type": "field" },
       { "params": [ "* -1" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$HOST$/" }
     ]
    }
   ]
  },
  {
   "title": "Disk IOPS",
   "type": "graph",
   "description": "Disk IOPS",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "alias": "系统总IOPS",
     "groupBy": [
      { "params": [ "network_interface_name" ], "type": "tag" }
     ],
     "measurement": "network_interfaces",
     "query": "SELECT   \"xfers\" FROM \"disk_total\" WHERE (\"host\" =~ /^$HOST$/) AND $timeFilter",
     "select": [
      [
       { "params": [ "ibytes" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$HOST$/" }
     ]
    },
    {
     "alias": "[[tag_disk_name]]",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT  \"xfers\" FROM \"disks\" WHERE (\"host\" =~ /^$HOST$/) AND $timeFilter GROUP BY \"disk_name\"",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "所有rac_data盘IOPS",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT   sum(\"xfers\") FROM \"disks\" WHERE (\"host\" =~ /^$HOST$/ and \"disk_name\" =~ /rac_data/ ) AND $timeFilter GROUP BY  time(5s)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "网络包数量(/S)",
   "type": "graph",
   "description": "网络包数量(/S)",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "alias": "[[tag_network_interface_name]].in",
     "groupBy": [
      { "params": [ "network_interface_name" ], "type": "tag" }
     ],
     "measurement": "network_interfaces",
     "query": "SELECT \"ipackets\" FROM \"network_interfaces\" WHERE (\"host\" =~ /^$HOST$/) AND $timeFilter GROUP BY \"network_interface_name\"",
     "select": [
      [
       { "params": [ "ibytes" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$HOST$/" }
     ]
    },
    {
     "alias": "[[tag_network_interface_name]].out",
     "groupBy": [
      { "params": [ "network_interface_name" ], "type": "tag" }
     ],
     "measurement": "network_interfaces",
     "query": "SELECT \"opackets\" * -1 FROM \"network_interfaces\" WHERE (\"host\" =~ /^$HOST$/) AND $timeFilter GROUP BY \"network_interface_name\"",
     "select": [
      [
       { "params": [ "obytes" ], "type": "field" },
       { "params": [ "* -1" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$HOST$/" }
     ]
    }
   ]
  },
  {
   "title": "Disk IO读写吞吐量(MB/S)",
   "type": "graph",
   "description": "Disk IO读写吞吐量(MB/S)",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "alias": "write",
     "groupBy": [
      { "params": [ "network_interface_name" ], "type": "tag" }
     ],
     "measurement": "network_interfaces",
     "query": "SELECT   \"write_blks\" * 512 / 1024 / 1024 FROM \"disk_total\" WHERE (\"host\" =~ /^$HOST$/) AND $timeFilter",
     "select": [
      [
       { "params": [ "ibytes" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$HOST$/" }
     ]
    },
    {
     "alias": "read",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT   \"read_blks\" * 512 / 1024 / 1024 FROM \"disk_total\" WHERE (\"host\" =~ /^$HOST$/) AND $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "各类进程占用CPU时间比例(%)",
   "type": "graph",
   "description": "各类进程占用CPU时间比例(%)",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 58 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "alias": "[[tag_processe_name]]",
     "groupBy": [
      { "params": [ "disk_name" ], "type": "tag" }
     ],
     "measurement": "disks",
     "query": "SELECT  \"ucpu_time\" + \"scpu_time\" FROM \"processes\" WHERE (\"host\" =~ /^$HOST$/) AND $timeFilter GROUP BY \"processe_name\"",
     "select": [
      [
       { "params": [ "busy" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$HOST$/" }
     ]
    }
   ]
  },
  {
   "title": "Disk IO平均相应时间(ms)",
   "type": "graph",
   "description": "Disk IO平均相应时间(ms)",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 59 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "alias": "write",
     "groupBy": [
      { "params": [ "network_interface_name" ], "type": "tag" }
     ],
     "measurement": "network_interfaces",
     "query": "SELECT   \"wserv\" / 1000000000  FROM \"disk_total\" WHERE (\"host\" =~ /^$HOST$/) AND $timeFilter",
     "select": [
      [
       { "params": [ "ibytes" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$HOST$/" }
     ]
    },
    {
     "alias": "read",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT   \"rserv\" / 1000000000  FROM \"disk_total\" WHERE (\"host\" =~ /^$HOST$/) AND $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Disk IO队列等待时间(ms)",
   "type": "graph",
   "description": "Disk IO队列等待时间(ms)",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 67 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "alias": "IO队列等待时间",
     "groupBy": [
      { "params": [ "network_interface_name" ], "type": "tag" }
     ],
     "measurement": "network_interfaces",
     "query": "SELECT   \"wq_time\" / 1000000000  FROM \"disk_total\" WHERE (\"host\" =~ /^$HOST$/) AND $timeFilter",
     "select": [
      [
       { "params": [ "ibytes" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$HOST$/" }
     ]
    }
   ]
  },
  {
   "title": "各进程占用内存(KB)",
   "type": "graph",
   "description": "各进程占用内存(KB)",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 71 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "[[tag_processe_name]]",
     "groupBy": [
      { "params": [ "disk_name" ], "type": "tag" }
     ],
     "measurement": "disks",
     "query": "SELECT  \"real_inuse\" FROM \"processes\" WHERE (\"host\" =~ /^$HOST$/) AND $timeFilter GROUP BY \"processe_name\"",
     "select": [
      [
       { "params": [ "busy" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$HOST$/" }
     ]
    }
   ]
  },
  {
   "title": "文件系统使用率(%)",
   "type": "graph",
   "description": "文件系统使用率(%)",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 75 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "[[tag_filesystem_name]]",
     "groupBy": [
      { "params": [ "filesystem_name" ], "type": "tag" }
     ],
     "measurement": "filesystems",
     "query": "SELECT \"used_percent\" FROM \"filesystems\" WHERE (\"host\" =~ /^$HOST$/) AND $timeFilter GROUP BY \"filesystem_name\"",
     "select": [
      [
       { "params": [ "used_percent" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$HOST$/" }
     ]
    }
   ]
  },
  {
   "title": "各进程占用计算内存(KB)",
   "type": "graph",
   "description": "各进程占用计算内存(KB)",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 82 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "[[tag_processe_name]]",
     "groupBy": [
      { "params": [ "disk_name" ], "type": "tag" }
     ],
     "measurement": "disks",
     "query": "SELECT  \"real_inuse\" - \"filepages\" FROM \"processes\" WHERE (\"host\" =~ /^$HOST$/) AND $timeFilter GROUP BY \"processe_name\"",
     "select": [
      [
       { "params": [ "busy" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$HOST$/" }
     ]
    }
   ]
  },
  {
   "title": "交换空间使用百分比(%)",
   "type": "graph",
   "description": "交换空间使用百分比(%)",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 83 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "alias": "计算内存百分比(%)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT  (\"mb_used\" * 100 / \"mb_size\")  FROM \"paging_spaces\" WHERE (\"host\" =~ /^$HOST$/) AND $timeFilter ",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  }
 ]
}